apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: agent
  name: agent
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: agent
