apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\k8s\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: clickhouse
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clickhouse
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\k8s\kompose.exe convert
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: clickhouse
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_DB
              value: lumen_db
            - name: CLICKHOUSE_PASSWORD
              value: lumenlog2026
            - name: CLICKHOUSE_USER
              value: default
          image: clickhouse/clickhouse-server:23.8
          name: clickhouse
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/clickhouse
              name: clickhouse-data
            - mountPath: /docker-entrypoint-initdb.d/init.sql
              name: clickhouse-cm1
              subPath: init.sql
      restartPolicy: Always
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: clickhouse-data
        - configMap:
            items:
              - key: init.sql
                path: init.sql
            name: clickhouse-cm1
          name: clickhouse-cm1
